Add modified configfiles

diff --git a/snakefiles/hybrid_snakefile b/snakefiles/hybrid_snakefile
--- a/snakefiles/hybrid_snakefile
+++ b/snakefiles/hybrid_snakefile
@@ -1,8 +1,8 @@
 import os
 data_dir = config["outdir"] 
 current_directory = os.getcwd()
-db_dir = os.path.join(current_directory,"databases")
-tools_dir = os.path.join(current_directory,"tools")
+db_dir = config["path_to_db_dir"]
+tools_dir = config["path_to_tools_dir"]
 rule all:  # type: ignore
     input:
         expand(  # type: ignore
@@ -109,26 +109,41 @@ rule FastQC_pretrim:
 
 rule Trimmomatic:
     input:
-        r1=lambda wildcards:config["samples"][wildcards.sample]["R1"],
-        r2=lambda wildcards:config["samples"][wildcards.sample]["R2"],
         valid_taxa=os.path.join(data_dir, "{sample}/logs/{sample}_validate_taxa.done"),
+        r1 = lambda wc: config["samples"][wc.sample]["R1"],
+        r2 = lambda wc: config["samples"][wc.sample]["R2"]
     output:
-        forward_paired=os.path.join(data_dir, "{sample}/01_trimmed_reads/forward_paired.fastq.gz"),
-        forward_unpaired=os.path.join(data_dir, "{sample}/01_trimmed_reads/forward_unpaired.fastq.gz"),
-        reverse_paired=os.path.join(data_dir, "{sample}/01_trimmed_reads/reverse_paired.fastq.gz"),
-        reverse_unpaired=os.path.join(data_dir, "{sample}/01_trimmed_reads/reverse_unpaired.fastq.gz"),
+        fwd_paired   = os.path.join(data_dir, "{sample}", "01_trimmed_reads", "forward_paired.fastq.gz"),
+        fwd_unpaired = os.path.join(data_dir, "{sample}", "01_trimmed_reads", "forward_unpaired.fastq.gz"),
+        rev_paired   = os.path.join(data_dir, "{sample}", "01_trimmed_reads", "reverse_paired.fastq.gz"),
+        rev_unpaired = os.path.join(data_dir, "{sample}", "01_trimmed_reads", "reverse_unpaired.fastq.gz")
+    threads: 10
+    resources:
+        mem_mb = lambda wc, threads: threads * 2000
     params:
-        options=lambda wildcards:config["parameters"]["Trimmomatic"],
+        extra = "SLIDINGWINDOW:4:15 MINLEN:36",
+        xmx   = lambda wc, resources: f"-Xmx{resources.mem_mb // 1024}g"
+    log:
+        os.path.join(data_dir, "{sample}", "logs", "trimmomatic.log")
     conda:
         "envs/trimmomatic.yaml"
-    log:
-        os.path.join(data_dir,"{sample}/logs/trimmomatic.log"),
-    threads:
-        10
     shell:
-        """
-         trimmomatic PE -threads {threads} -phred33 {input.r1} {input.r2} {output.forward_paired} {output.forward_unpaired} {output.reverse_paired} {output.reverse_unpaired} {params.options} &> {log}
-        """
+        r"""
+        echo ">>> Running Trimmomatic with {params.xmx}" > {log}
+        echo ">>> Active conda env: $CONDA_PREFIX" >> {log}
+        JAR=$(find $CONDA_PREFIX/share -name "trimmomatic.jar" | head -n1)
+        if [ ! -s "$JAR" ]; then
+            echo "ERROR: Could not find Trimmomatic jar in $CONDA_PREFIX/share" >> {log}
+            exit 1
+        fi
+        java {params.xmx} -jar $JAR PE \
+            -threads {threads} -phred33 \
+            {input.r1} {input.r2} \
+            {output.fwd_paired} {output.fwd_unpaired} \
+            {output.rev_paired} {output.rev_unpaired} \
+            {params.extra} \
+            &>> {log}
+        """ 
 
 rule FastQC_posttrim:
     input:  
@@ -230,7 +245,7 @@ rule CheckM_post_assembly:
     params:
         assembly_dir=os.path.join(data_dir, "{sample}/02_flye/"),
         outdir=os.path.join(data_dir,"{sample}/05_checkm/post_assembly"),
-        db_path=os.path.join(db_dir,"checkm"),
+        db_path=os.path.join(db_dir,"ganga_databases","checkm"),
         options=lambda wildcards:config["parameters"]["checkm"]["options"],
     log:
         os.path.join(data_dir,"{sample}/logs/checkm_post_assembly.log")
@@ -262,7 +277,7 @@ rule CheckM_post_polish:
     params:
         assembly_dir=os.path.join(data_dir, "{sample}/02_flye/"),
         outdir=os.path.join(data_dir,"{sample}/05_checkm/post_polish"),
-        db_path=os.path.join(db_dir,"checkm"),
+        db_path=os.path.join(db_dir,"ganga_databases","checkm"),
         options=lambda wildcards:config["parameters"]["checkm"]["options"],
     log:
         os.path.join(data_dir,"{sample}/logs/checkm_post_polish.log")
@@ -396,6 +411,7 @@ rule Pilon:
     output:
         assembly=os.path.join(data_dir, "{sample}/04_pilon/{sample}.fasta"),
         final=os.path.join(data_dir, "{sample}/04_pilon/{sample}_final.fasta"),
+        mobile_fasta=os.path.join(data_dir, "{sample}/13_mobileog/{sample}_final.fasta"),
     params:
         outdir=os.path.join(data_dir, "{sample}/04_pilon"),
         name="{sample}",
@@ -428,6 +444,7 @@ rule Pilon:
         done < {output.final}
         rm {output.final}
         mv {params.temp_fasta} {output.final}
+        cp {output.final} {output.mobile_fasta}
         """
 
 rule Prodigal:
@@ -468,7 +485,7 @@ rule Bakta:
         genus=lambda wildcards:config["samples"][wildcards.sample]["genus"],
         species=lambda wildcards:config["samples"][wildcards.sample]["species"],
         outdir=os.path.join(data_dir, "{sample}/09_bakta"),
-        db_path=os.path.join(db_dir,"bakta_db/db"),
+        db_path=os.path.join(db_dir,"ganga_databases","bakta_db/db"),
         options=lambda wildcards:config["parameters"]["Bakta"]["options"],
     log:
         os.path.join(data_dir,"{sample}/logs/bakta.log")
@@ -510,7 +527,7 @@ rule RGI:
     params:
         prefix=os.path.join(data_dir, "{sample}/11_rgi/{sample}_rgi"),
         options=lambda wildcards:config["parameters"]["RGI"],
-        tools_dir=tools_dir,
+        tools_dir=os.path.join(tools_dir, "ganga_tools"),
         cd=current_directory
     log:
         os.path.join(data_dir,"{sample}/logs/rgi.log")
@@ -543,15 +560,17 @@ rule Phigaro:
     params:
         outdir=os.path.join(data_dir, "{sample}/12_phigaro/"),
         options=lambda wildcards:config["parameters"]["Phigaro"],
+        config=os.path.join(db_dir,"ganga_databases/phigaro/config.yml"),
     log:
         os.path.join(data_dir,"{sample}/logs/phigaro.log")
     threads:
         20
     shell:
-        """
-               
-        phigaro -o {params.outdir} -f {input.assembly} {params.options} -e tsv html --not-open -t {threads} &> {log}
-	"""
+        """    
+        cd {db_dir}/ganga_databases/phigaro
+        phigaro -o {params.outdir} -c {params.config} -f {input.assembly} {params.options} -e tsv html --not-open -t {threads} &> {log}
+        cd {current_directory}
+	    """
 
 rule EzAAI:
     input:
@@ -586,21 +605,22 @@ rule EzAAI:
 rule mobileOG_db:
     input:
         flag=os.path.join(current_directory, "flags/mobileogdb.done"),
-        assembly=os.path.join(data_dir, "{sample}/04_pilon/{sample}_final.fasta"),
+        assembly=os.path.join(data_dir, "{sample}/13_mobileog/{sample}_final.fasta"),
     output:
         alignment_out_csv=os.path.join(data_dir,"{sample}/13_mobileog/{sample}_final.fasta.mobileOG.Alignment.Out.csv"),
         summary_csv=os.path.join(data_dir,"{sample}/13_mobileog/{sample}_final.fasta.summary.csv"),
         tsv=os.path.join(data_dir,"{sample}/13_mobileog/{sample}_final.fasta.tsv"),
     params:
         options=lambda wildcards:config["parameters"]["mobileog"]["options"],
-        mobileog_dmnd=os.path.join(tools_dir,"mobileOg/mobileOG-db-main/mobileog_db.dmnd"),
-        mobileog_csv=os.path.join(tools_dir,"mobileOg/mobileOG-db-main/mobileog_db.csv"),
-        shellscript=os.path.join(tools_dir,"mobileOg/mobileOG-db-main/mobileOG-pl/mobileOGs-pl-kyanite.sh"),
+        mobileog_dmnd=os.path.join(tools_dir,"ganga_tools/mobileOg/mobileOG-db-main/mobileog_db.dmnd"),
+        mobileog_csv=os.path.join(tools_dir,"ganga_tools/mobileOg/mobileOG-db-main/mobileog_db.csv"),
+        shellscript=os.path.join(tools_dir,"ganga_tools/mobileOg/mobileOG-db-main/mobileOG-pl/mobileOGs-pl-kyanite.sh"),
         outdir=os.path.join(data_dir,"{sample}/13_mobileog/"),
         premoved_alignment_out_csv=os.path.join(data_dir,"{sample}/04_pilon/{sample}_final.fasta.mobileOG.Alignment.Out.csv"),
         premoved_summary_csv=os.path.join(data_dir,"{sample}/04_pilon/{sample}_final.fasta.summary.csv"),
         premoved_tsv=os.path.join(data_dir,"{sample}/04_pilon/{sample}_final.fasta.tsv"),
-        cd=current_directory
+        cd=current_directory,
+        tools_dir=tools_dir,
     threads:
         20
     conda:
@@ -612,16 +632,14 @@ rule mobileOG_db:
         if [ ! -d "{params.outdir}" ]; then 
         mkdir {params.outdir}
         fi
-        cd tools/mobileOg/mobileOG-db-main/mobileOG-pl
+        cd {params.tools_dir}/ganga_tools
+        cd mobileOg/mobileOG-db-main/mobileOG-pl
         bash {params.shellscript} -i {input.assembly} -d {params.mobileog_dmnd} -m {params.mobileog_csv} {params.options} &> {log}
         cd {params.cd}
-        mv {params.premoved_alignment_out_csv} {output.alignment_out_csv}
-        mv {params.premoved_summary_csv} {output.summary_csv}
-        mv {params.premoved_tsv} {output.tsv}
+        #mv {params.premoved_alignment_out_csv} {output.alignment_out_csv}
+        #mv {params.premoved_summary_csv} {output.summary_csv}
+        #mv {params.premoved_tsv} {output.tsv}
         """
-
-
-
 
 
 rule pocp:
@@ -636,6 +654,8 @@ rule pocp:
         revision="2.3.0",
         profile=["local", "conda"],
         output=os.path.join(data_dir,"{sample}/07_pocp"),
+        cd=current_directory,
+        tools_dir=tools_dir,
     log:
         os.path.join(data_dir,"{sample}/logs/pocp.log")
     threads:
@@ -644,11 +664,11 @@ rule pocp:
         "envs/pocp.yaml"
     shell:
         """
+        cd {params.tools_dir}/ganga_tools/pocp
         nextflow run hoelzer/pocp -r 2.3.0 --genomes {input.genomes} --genome {input.genome} -profile local,conda --output {params.output} 2> {log}
+        cd {params.cd}
         """
        
-
-
 
 rule GenoVI:
     input:
@@ -672,6 +692,8 @@ rule GenoVI:
         "envs/genovi.yaml"
     shell:
         """
+        mkdir -p {params.outdir}
+        cd {params.outdir}
         contig_count=$(grep -c '^>' {input.pilon})
         if [ "$contig_count" -le 250 ]; then
         genovi -i {input.bakta} -o genovi -s draft --title {params.sample_name} --cogs {params.COGs} {params.options} &> {log}
@@ -739,29 +761,12 @@ rule CRISPRcasIdentifier:
         "envs/crispr.yaml"
     shell:
         """
-        cd {params.tools_dir}
+        cd {params.tools_dir}/ganga_tools
         cd crispr/CRISPRcasIdentifier-1.1.0
         python CRISPRcasIdentifier.py -f {input.assembly} {params.options} -o {output} &> {log}
         cd {params.cd}
         """
-
         
-        
-rule Panvita_setup:
-    input:
-
-    output:
-        os.path.join(current_directory, "flags/panvita.done"),
-
-    conda:
-        "envs/panvita.yaml"
-    shell:
-        """
-        git clone https://github.com/dlnrodrigues/panvita.git
-        echo -n > {output}
-        """
-
-
 rule Panvita:
     input:
         flag=os.path.join(current_directory, "flags/panvita.done"),
@@ -771,7 +776,7 @@ rule Panvita:
     params:
         outdir_path=os.path.join(data_dir,"{sample}/16_panvita/"),
         cd=current_directory,
-        panvita_path=os.path.join(tools_dir,"panvita/panvita.py")
+        panvita_path=os.path.join(db_dir, "ganga_databases", "panvita/panvita.py")
     log:
         os.path.join(data_dir,"{sample}/logs/{sample}_panvita.log"),
     threads:
@@ -798,6 +803,7 @@ rule Antismash:
     params:
         outdir=os.path.join(data_dir,"{sample}/18_antismash"),
         sample_name="{sample}",
+        antismash_db_path=os.path.join(db_dir,"ganga_databases","antismash"),
         options=lambda wildcards:config["parameters"]["antismash"]["options"],
     log:
         os.path.join(data_dir,"{sample}/logs/antismash.log")
@@ -807,7 +813,8 @@ rule Antismash:
         "envs/antismash.yaml"
     shell:
         """
-        antismash -t bacteria --output-dir {params.outdir} --output-basename {params.sample_name} --genefinding-tool none {input.bakta_gbff} {params.options} &> {log}
+        antismash -t bacteria --databases {params.antismash_db_path} --output-dir {params.outdir} --output-basename {params.sample_name} --genefinding-tool none {input.bakta_gbff} {params.options} &> {log}
+        """
 
 rule create_absolute_paths:
     input:
